### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by xessam** [kheruc/rt-nested-layouts#6]
@kheruc what if i want to wrap my component in router or something like that

for example in docs page:

import { withRouter } from "next/router";
import DocsLayout from '../../components/layouts/docs';
const DocsPage = () => ();

DocsPage.Layout = DocsLayout;

export default withRouter(DocsPage);
<hr>

or i restricted some pages with ProtectRoute wrapper like this:

.../ProtectRoute.jsx
function ProtectRoute(Component) {
    return () => {

    const { authenticated, loading } = useAuth();
    const router = useRouter();

    useEffect(() => {
        if (!authenticated && !loading) router.push('/user/login')
    }, [loading, authenticated]);
   
    return (!loading && authenticated && <Component {...arguments} />)
    }
 }
<hr>

in this case how to access page layout from component object in _app.js? Component.Layout is going to be undefined
 const Layouter = Component.Layout || Layout;

and sorry for my english

**Comment by lululuting** [comment]
Package first and then assign value
<img width="717" alt="image" src="https://user-images.githubusercontent.com/26959652/153843407-21a7f423-3a5c-4999-8496-81944b33330e.png">
